Repository andrewhamerly/poker-pulse, pull requests merged in 2024-08, with the labels that each got.

#94 fixed error in Schedule/Event and changed character in multiDay
  client/src/components/Schedule/multiDay.jsx
  client/src/pages/Event.jsx
  client/src/pages/Schedule.jsx
Labels: bug

#99 Not logged in users now see please login on schedule page
  client/src/components/Schedule/HorizontalTable.jsx
  client/src/components/Schedule/Schedule.css
Labels: enhancement

#106 Changed wording if user isn't logged in
  client/src/components/Schedule/HorizontalTable.jsx
Labels: documentation

#107 Added signup modal to schedule page / changed login text to match signup
  client/src/components/Schedule/HorizontalTable.jsx
  client/src/pages/Login.jsx
Labels: documentation, enhancement

#115 Got filter working with event page.
  client/src/components/Event/HorizontalEvent.jsx
  client/src/components/Event/VerticalEvent.jsx
  client/src/components/Event/eventFilters.jsx
  client/src/components/Schedule/Schedule.css
  client/src/components/Schedule/VerticalTable.jsx
  client/src/pages/FilterPage.jsx
Labels: documentation, enhancement

#116 Rename eventFilters.jsx to EventFilters.jsx
  client/src/components/Event/EventFilters.jsx
Labels: bug, documentation

#119 Fixed styling for Add Events button in V&H schedule pages.
  client/src/components/Schedule/HorizontalTable.jsx
  client/src/components/Schedule/Schedule.css
  client/src/components/Schedule/VerticalTable.jsx
Labels: documentation

#123 Added spinner for loading screens
  client/src/components/Event/EventDetails.jsx
  client/src/components/Event/HorizontalEvent.jsx
  client/src/components/Event/VerticalEvent.jsx
  client/src/pages/Home.jsx
Labels: enhancement

#126 Refined Event/Schedule Components
  client/src/App.jsx
  client/src/components/Event/EventDetails.jsx
  client/src/components/Event/EventFilters.jsx
  client/src/components/Event/EventTableandFilters.jsx
  client/src/components/Event/HorizontalEvent.jsx
  client/src/components/Event/VerticalEvent.jsx
  client/src/components/Schedule/HorizontalTable.jsx
  client/src/components/Schedule/ScheduleTable.jsx
  client/src/components/Schedule/VerticalTable.jsx
  client/src/contexts/EventFilterContext.jsx
  client/src/pages/Event.jsx
  client/src/pages/Schedule.jsx
  client/src/utils/scheduleHelper.js
Labels: documentation, enhancement

#127 changed name of helper file
  client/src/components/Event/EventFilters.jsx
  client/src/components/Event/EventTableandFilters.jsx
  client/src/components/Schedule/ScheduleTable.jsx
  client/src/components/Schedule/absentTitle.jsx
  client/src/components/Schedule/formattedChips.jsx
  client/src/components/Schedule/formattedDate.jsx
  client/src/components/Schedule/formattedEntryFee.jsx
  client/src/components/Schedule/formattedLevels.jsx
  client/src/components/Schedule/formattedTime.jsx
  client/src/components/Schedule/guaranteePrefix.jsx
  client/src/pages/Event.jsx
  client/src/pages/FilterPage.jsx
  client/src/pages/Home.jsx
  client/src/utils/EventAndScheduleHelpers.js
Labels: documentation

#132 Fixed casing of EventTableandFilters in imports
  client/src/pages/Event.jsx
Labels: documentation

#133 Rename EventTableandFilters.jsx to EventTableAndFilters.jsx
  client/src/components/Event/EventTableAndFilters.jsx
Labels: documentation
